<img src="https://res.cloudinary.com/practicaldev/image/fetch/s--oTgfo1EL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png">

In [1]:
''' import numpy as np 
"""

one dimention array is called as vector and
 dimention are called as axes
"""

#a=np.array()

a.ndim
a.itemsize
a.size
a.shape
a.nbytes

a.dtype #a = np.array([1, 2, 3], dtype=np.float64)

	#arr = np.array([1, 2, 3, 4], dtype='S')
"""

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

"""




# numpy zeros

a = np.zeros((2, 3),dtype=np.int32) # by default the dtype is float64
print(a)
 
# numpy ones

a = np.ones((2, 3, 2))

"""

c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

"""


#two dimention Array we pass a list of a list of integers to the array() function.
	#A two-dimensional array is also called a matrix.
b = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)




#three dimention #Note that a 3-D array is also called a tensor.


c = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
    ]
)




"""
To find the number of axes and the number of elements
 on each axis of an array, you use the shape property. For example:
a.ndim
a.shape

The shape property returns a tuple

The numpy arange() function creates a new numpy array with
 evenly spaced numbers between start (inclusive) and stop (exclusive)
 with a given step:
"""
 
a = np.arange(1, 10, 2, dtype=np.float64)
#c[1,3]
c[1:2:3,:]'''


' import numpy as np \n"""\n\none dimention array is called as vector and\n dimention are called as axes\n"""\n\n#a=np.array()\n\na.ndim\na.itemsize\na.size\na.shape\na.nbytes\n\na.dtype #a = np.array([1, 2, 3], dtype=np.float64)\n\n\t#arr = np.array([1, 2, 3, 4], dtype=\'S\')\n"""\n\ni - integer\nb - boolean\nu - unsigned integer\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )\n\n"""\n\n\n\n\n# numpy zeros\n\na = np.zeros((2, 3),dtype=np.int32) # by default the dtype is float64\nprint(a)\n \n# numpy ones\n\na = np.ones((2, 3, 2))\n\n"""\n\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )\n\n"""\n\n\n#two dimention Array we pass a list of a list of integers to the array() function.\n\t#A two-dimensional array is also called a matrix.\nb = np.array(\n    [\n        [1, 2, 3],\n        [4, 5,

In [7]:
import numpy as np


In [8]:
a = np.ones((2, 3, 2,4))
a=np.array([[[[1.0, 1.0, 1.0, 1.0],
   [1.0 ,10.0 ,1.0, 1.0]],
   [[1.0, 1.0, 1.0, 1.0],
   [1.0 ,10.0 ,1.0, 1.0]]],
   [[[1.0, 1.0, 1.0, 1.0],
   [1.0 ,10.0 ,1.0, 1.0]],
   [[1.0, 1.0, 1.0, 1.0],
   [1.0 ,10.0 ,1.0, 1.0]]]])

 
a.ndim
a.shape

(2, 2, 2, 4)

In [9]:
import numpy as np
a=np.array(['1',2,3])

In [10]:
a.dtype

dtype('<U11')

In [24]:
a=np.arange(1,10,0.1)#start stop step

In [29]:
a.reshape(3,2,3,5)

array([[[[1. , 1.1, 1.2, 1.3, 1.4],
         [1.5, 1.6, 1.7, 1.8, 1.9],
         [2. , 2.1, 2.2, 2.3, 2.4]],

        [[2.5, 2.6, 2.7, 2.8, 2.9],
         [3. , 3.1, 3.2, 3.3, 3.4],
         [3.5, 3.6, 3.7, 3.8, 3.9]]],


       [[[4. , 4.1, 4.2, 4.3, 4.4],
         [4.5, 4.6, 4.7, 4.8, 4.9],
         [5. , 5.1, 5.2, 5.3, 5.4]],

        [[5.5, 5.6, 5.7, 5.8, 5.9],
         [6. , 6.1, 6.2, 6.3, 6.4],
         [6.5, 6.6, 6.7, 6.8, 6.9]]],


       [[[7. , 7.1, 7.2, 7.3, 7.4],
         [7.5, 7.6, 7.7, 7.8, 7.9],
         [8. , 8.1, 8.2, 8.3, 8.4]],

        [[8.5, 8.6, 8.7, 8.8, 8.9],
         [9. , 9.1, 9.2, 9.3, 9.4],
         [9.5, 9.6, 9.7, 9.8, 9.9]]]])

In [38]:
a = np.linspace(1,1.1, 8)#start stop n-number of element

In [39]:
a

array([1.        , 1.01428571, 1.02857143, 1.04285714, 1.05714286,
       1.07142857, 1.08571429, 1.1       ])

In [41]:
a.ndim;a.shape;a.nbytes;a.size
type(a)

numpy.ndarray

In [57]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a>5#bool
five_up = (a[a > 5])#values
print(five_up)
np.nonzero(a>5)#position

[ 6  7  8  9 10 11 12]


(array([1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [10]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [43]:
if 11>2 and 3<2:
    print('hello')

In [11]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [12]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [54]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  0, 12]])

In [53]:
b = np.nonzero(a ==10) ##search element with some condition
print(b) 

(array([2], dtype=int64), array([1], dtype=int64))


In [14]:
e=np.eye(5)
f = np.nonzero(e == 1)
print(f)

(array([0, 1, 2, 3, 4], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64))


In [15]:
b = np.nonzero(a > 5) ##search element with some condition
print(b) 
list_of_coordinates= zip(f[0],b[0], b[1])
for coord in list_of_coordinates:
    print(coord)

(array([1, 1, 1, 2, 2, 2, 2], dtype=int64), array([1, 2, 3, 0, 1, 2, 3], dtype=int64))
(0, 1, 1)
(1, 1, 2)
(2, 1, 3)
(3, 2, 0)
(4, 2, 1)


<img src="numpy-array-indexing-2d-array.svg">

In [68]:
print(a)
print(np.max(a[:,1]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
10


<img src="numpy-array-indexing-3d-array.svg">